# Generated by Django 5.0.7 on 2024-08-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentalSalesapp', '0002_category_user_avatar_user_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='origin',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rental',
            name='total_rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
