# Generated by Django 5.0.7 on 2024-08-08 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentalSalesapp', '0003_car_color_car_condition_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='car',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(default='', max_length=50)),
                ('transmission', models.CharField(default='', max_length=50)),
                ('seats', models.IntegerField(default=0)),
                ('interior_color', models.CharField(default='', max_length=50)),
                ('condition', models.CharField(default='', max_length=10)),
                ('origin', models.CharField(default='', max_length=10)),
                ('color', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_day', models.FloatField()),
                ('mileage', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carRentalSalesapp.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='favoritecar',
            name='rent_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentalSalesapp.rentcar'),
        ),
        migrations.AddField(
            model_name='image',
            name='rent_car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carRentalSalesapp.rentcar'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carRentalSalesapp.rentcar'),
        ),
        migrations.AlterField(
            model_name='review',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='carRentalSalesapp.rentcar'),
        ),
        migrations.CreateModel(
            name='SaleCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(default='', max_length=50)),
                ('transmission', models.CharField(default='', max_length=50)),
                ('seats', models.IntegerField(default=0)),
                ('interior_color', models.CharField(default='', max_length=50)),
                ('condition', models.CharField(default='', max_length=10)),
                ('origin', models.CharField(default='', max_length=10)),
                ('color', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carRentalSalesapp.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='favoritecar',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoritecar',
            name='sale_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentalSalesapp.salecar'),
        ),
        migrations.AddField(
            model_name='image',
            name='sale_car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carRentalSalesapp.salecar'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carRentalSalesapp.salecar'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carRentalSalesapp.salecar'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritecar',
            unique_together={('user', 'rent_car', 'sale_car')},
        ),
        migrations.RemoveField(
            model_name='favoritecar',
            name='car',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
